version: '3.4'

services:
  accesspoint:
    image: accesspoint
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4116:4116
